# Generated by Django 4.0.3 on 2022-07-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='担当者メールアドレス')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者氏名')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お客様氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='お客様メールアドレス')),
                ('subject', models.CharField(max_length=256, verbose_name='件名')),
                ('message', models.TextField(verbose_name='本文')),
                ('time', models.DateTimeField(blank=True, verbose_name='送信日時')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お客様氏名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='お客様メールアドレス')),
                ('newsletter', models.BooleanField(default=True, verbose_name='メルマガ希望')),
                ('valid', models.BooleanField(default=True, verbose_name='有効')),
                ('reject', models.BooleanField(default=False, verbose_name='拒否')),
                ('count', models.IntegerField(default=0, verbose_name='問い合わせ回数')),
            ],
        ),
        migrations.CreateModel(
            name='MailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254, verbose_name='送信メールアドレス')),
                ('enable', models.BooleanField(default=True, verbose_name='有効')),
            ],
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='email_idx'),
        ),
    ]
